# Generated by Django 2.2.3 on 2019-10-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date')),
                ('open', models.BooleanField(default=False, verbose_name='Open Notic')),
                ('text', models.TextField(blank=True, default='', max_length=1000, verbose_name='notic text')),
                ('image_url', models.CharField(blank=True, default='', max_length=1000, verbose_name='notic image URL')),
            ],
        ),
    ]
